// <auto-generated />
using System;
using System.Collections.Generic;
using AltusIQ.Api.Data;
using AltusIQ.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AltusIQ.Api.Migrations
{
    [DbContext(typeof(AltusIqDbContext))]
    [Migration("20260618200109_AddFlightEnrichmentFields")]
    partial class AddFlightEnrichmentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AltusIQ.Api.Models.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ArrivalAirport")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Callsign")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartureAirport")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnrichmentAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Icao24")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<double?>("LastAltitude")
                        .HasColumnType("double precision");

                    b.Property<Point>("LastPosition")
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginCountry")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<List<TrackPoint>>("TrackPoints")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("EnrichedAt");

                    b.HasIndex("Icao24");

                    b.HasIndex("LastPosition");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("LastPosition"), "gist");

                    b.HasIndex("OpenedAt");

                    b.ToTable("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
